In [18]:
import numpy as np

# 1) Array 

In [2]:
arr = np.array([1,2,3,4,5])
print (arr)

[1 2 3 4 5]


# 2)np.ones()
Bütün elemanları 1 olan bir dizi olustrur.

In [3]:
one_arr =np.ones((2,4))
print(one_arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# 3)np.arange()
Belirtilen aralıkta bir dizi olusturur

In [4]:
arr_range=np.arange(0,10,2)
print(arr_range)

[0 2 4 6 8]


# 4)np.linspace()
Belirtilen aralıkta esit aralıklı sayılar üretir.

In [6]:
lin_space=np.linspace(0,5,10)
print(lin_space)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


### 5)np.reshape()
Dizinin boyutlarını değiştirir.

In [8]:
arr=np.arange(1,10)
reshaped_arr=arr.reshape((3,3))
print(reshaped_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 6)np.random.rand()
0ile1 arasında rastgele degerler üretir.

In [14]:
random_arr = np.random.rand(3, 3)
print(random_arr) 

[[0.98110536 0.63287001 0.97751502]
 [0.13072048 0.03429949 0.608531  ]
 [0.68850265 0.26963622 0.37317644]]


# 7)np.mean()
Dizinin ortalamasını alır

In [23]:
print(np.mean(arr)) 

3.0


# 8)np.sum()
Dizideki tüm elemanların toplamını döndürür.

In [24]:
arr = np.array([1, 2, 3, 4, 5])
print(np.sum(arr))

15


# 9) np.max() 
Maksimum değeri bulur.

In [25]:
arr = np.array([10, 20, 5, 30])
print(np.max(arr))  

30


# 10)np.min()
Minimum değeri döndüür